spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:   
    password: 

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  transaction:
    platform: org.springframework.orm.jpa.JpaTransactionManager

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true